import type { RefundRecord } from './types';

export const demoRefunds: RefundRecord[] = [
  {
    id: 're_demo_001',
    amount: 4999,
    currency: 'cad',
    status: 'succeeded',
    reason: 'requested_by_customer',
    created: Math.floor(new Date('2026-01-02T10:30:00Z').getTime() / 1000),
    charge: 'ch_demo_001',
    description: 'Monthly subscription refund',
    customerEmail: 'alice@example.com',
    failureReason: null,
  },
  {
    id: 're_demo_002',
    amount: 12500,
    currency: 'cad',
    status: 'succeeded',
    reason: 'duplicate',
    created: Math.floor(new Date('2026-01-03T14:15:00Z').getTime() / 1000),
    charge: 'ch_demo_002',
    description: 'Duplicate charge refund',
    customerEmail: 'bob@company.com',
    failureReason: null,
  },
  {
    id: 're_demo_003',
    amount: 32000,
    currency: 'usd',
    status: 'succeeded',
    reason: 'fraudulent',
    created: Math.floor(new Date('2026-01-04T09:00:00Z').getTime() / 1000),
    charge: 'ch_demo_003',
    description: null,
    customerEmail: 'carol@startup.io',
    failureReason: null,
  },
  {
    id: 're_demo_004',
    amount: 1500,
    currency: 'cad',
    status: 'succeeded',
    reason: 'requested_by_customer',
    created: Math.floor(new Date('2026-01-05T16:45:00Z').getTime() / 1000),
    charge: 'ch_demo_004',
    description: 'Product not as described',
    customerEmail: 'dave@email.com',
    failureReason: null,
  },
  {
    id: 're_demo_005',
    amount: 8750,
    currency: 'usd',
    status: 'pending',
    reason: null,
    created: Math.floor(new Date('2026-01-06T11:20:00Z').getTime() / 1000),
    charge: 'ch_demo_005',
    description: 'Service cancellation',
    customerEmail: 'eve@business.net',
    failureReason: null,
  },
  {
    id: 're_demo_006',
    amount: 50000,
    currency: 'cad',
    status: 'succeeded',
    reason: 'requested_by_customer',
    created: Math.floor(new Date('2026-01-08T08:30:00Z').getTime() / 1000),
    charge: 'ch_demo_006',
    description: 'Annual plan cancellation — prorated',
    customerEmail: 'frank@corp.ca',
    failureReason: null,
  },
  {
    id: 're_demo_007',
    amount: 2200,
    currency: 'cad',
    status: 'failed',
    reason: 'duplicate',
    created: Math.floor(new Date('2026-01-09T13:00:00Z').getTime() / 1000),
    charge: 'ch_demo_007',
    description: 'Double charge — processing error',
    customerEmail: 'grace@shop.com',
    failureReason: 'insufficient_funds',
  },
  {
    id: 're_demo_008',
    amount: 19900,
    currency: 'usd',
    status: 'succeeded',
    reason: 'fraudulent',
    created: Math.floor(new Date('2026-01-10T17:10:00Z').getTime() / 1000),
    charge: 'ch_demo_008',
    description: null,
    customerEmail: null,
    failureReason: null,
  },
  {
    id: 're_demo_009',
    amount: 7500,
    currency: 'cad',
    status: 'succeeded',
    reason: 'requested_by_customer',
    created: Math.floor(new Date('2026-01-12T12:00:00Z').getTime() / 1000),
    charge: 'ch_demo_009',
    description: 'Returned item — order #4821',
    customerEmail: 'henry@store.ca',
    failureReason: null,
  },
  {
    id: 're_demo_010',
    amount: 3300,
    currency: 'usd',
    status: 'succeeded',
    reason: 'other',
    created: Math.floor(new Date('2026-01-13T10:45:00Z').getTime() / 1000),
    charge: 'ch_demo_010',
    description: 'Goodwill adjustment',
    customerEmail: 'iris@domain.com',
    failureReason: null,
  },
  {
    id: 're_demo_011',
    amount: 45000,
    currency: 'cad',
    status: 'succeeded',
    reason: 'requested_by_customer',
    created: Math.floor(new Date('2026-01-15T09:15:00Z').getTime() / 1000),
    charge: 'ch_demo_011',
    description: 'Enterprise subscription refund',
    customerEmail: 'jack@enterprise.com',
    failureReason: null,
  },
  {
    id: 're_demo_012',
    amount: 6600,
    currency: 'cad',
    status: 'pending',
    reason: 'duplicate',
    created: Math.floor(new Date('2026-01-16T14:30:00Z').getTime() / 1000),
    charge: 'ch_demo_012',
    description: 'Processing error — second charge',
    customerEmail: 'kate@freelance.ca',
    failureReason: null,
  },
  {
    id: 're_demo_013',
    amount: 11200,
    currency: 'usd',
    status: 'succeeded',
    reason: 'requested_by_customer',
    created: Math.floor(new Date('2026-01-18T15:00:00Z').getTime() / 1000),
    charge: 'ch_demo_013',
    description: 'Partial refund — service downtime',
    customerEmail: 'liam@tech.io',
    failureReason: null,
  },
  {
    id: 're_demo_014',
    amount: 28000,
    currency: 'cad',
    status: 'succeeded',
    reason: 'fraudulent',
    created: Math.floor(new Date('2026-01-20T11:30:00Z').getTime() / 1000),
    charge: 'ch_demo_014',
    description: null,
    customerEmail: 'mia@startup.ca',
    failureReason: null,
  },
  {
    id: 're_demo_015',
    amount: 5500,
    currency: 'cad',
    status: 'succeeded',
    reason: 'requested_by_customer',
    created: Math.floor(new Date('2026-01-21T16:20:00Z').getTime() / 1000),
    charge: 'ch_demo_015',
    description: 'Plan downgrade credit',
    customerEmail: 'noah@brand.co',
    failureReason: null,
  },
  {
    id: 're_demo_016',
    amount: 1000,
    currency: 'usd',
    status: 'succeeded',
    reason: 'other',
    created: Math.floor(new Date('2026-01-23T08:00:00Z').getTime() / 1000),
    charge: 'ch_demo_016',
    description: 'Promotional credit refund',
    customerEmail: 'olivia@media.com',
    failureReason: null,
  },
  {
    id: 're_demo_017',
    amount: 38000,
    currency: 'cad',
    status: 'succeeded',
    reason: 'requested_by_customer',
    created: Math.floor(new Date('2026-01-25T13:45:00Z').getTime() / 1000),
    charge: 'ch_demo_017',
    description: 'Unused services credit — Q1',
    customerEmail: 'peter@legal.ca',
    failureReason: null,
  },
  {
    id: 're_demo_018',
    amount: 9800,
    currency: 'usd',
    status: 'pending',
    reason: 'fraudulent',
    created: Math.floor(new Date('2026-01-27T10:10:00Z').getTime() / 1000),
    charge: 'ch_demo_018',
    description: null,
    customerEmail: 'quinn@protect.net',
    failureReason: null,
  },
  {
    id: 're_demo_019',
    amount: 16500,
    currency: 'cad',
    status: 'succeeded',
    reason: 'duplicate',
    created: Math.floor(new Date('2026-01-28T12:30:00Z').getTime() / 1000),
    charge: 'ch_demo_019',
    description: 'System error — duplicate billing',
    customerEmail: 'rachel@agency.ca',
    failureReason: null,
  },
  {
    id: 're_demo_020',
    amount: 22200,
    currency: 'cad',
    status: 'succeeded',
    reason: 'requested_by_customer',
    created: Math.floor(new Date('2026-01-30T09:00:00Z').getTime() / 1000),
    charge: 'ch_demo_020',
    description: 'End-of-month subscription cancellation',
    customerEmail: 'sam@consulting.ca',
    failureReason: null,
  },
];
